modLoader="javafml"
loaderVersion="[36,)"
license="All-Rights-Reserved"
[[mods]]
modId="smpessentials"
version="1.0"
displayName="SMP Essentials"
authors="Khajiitos"
description='''SMP Essentials'''

[[dependencies.smpessentials]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.smpessentials]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,)"
   ordering="NONE"
   side="BOTH"
